# Generated by Django 5.2.3 on 2025-06-27 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_address_alter_patient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
