# Generated by Django 5.2.3 on 2025-06-28 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_verified_patient_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='reset_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
