# Generated by Django 5.2.3 on 2025-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token_used',
            field=models.BooleanField(default=False),
        ),
    ]
