# Generated by Django 5.2.3 on 2025-06-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
